actions:
  abortActions: []
  emailNotifications: []
  setVariableActions:
  - description: null
    exitCodes: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    status: Success
    sysId: ed98f9ed8ab84e4fbcc0f1e2978a7c2a
    variableName: time1
    variableScope: Self
    variableValue: ${_formatDate('${ops_launch_time}','HH',0,'',-1)}
  snmpNotifications: []
  systemOperations: []
avgRunTime: 0
avgRunTimeDisplay: 0 Seconds
cpDuration: null
cpDurationUnit: Minutes
customField1:
  label: null
  value: null
customField2:
  label: null
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
enforceVariables: false
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.6.3.2
exportTable: ops_task_sleep
firstRun: 2025-01-22 06:57:13 -0500
holdResources: false
lastRun: 2025-02-07 09:22:15 -0500
lastRunTime: 0
lastRunTimeDisplay: 0 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
lockVariables: false
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 0
maxRunTimeDisplay: 0 Seconds
minRunTime: 0
minRunTimeDisplay: 0 Seconds
name: Sleep 0
notes: []
opswiseGroups: []
overrideInstanceWait: 'No'
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 4
runTime: 0
simulation: true
sleepAmount: '1'
sleepDayConstraint: None
sleepDuration: 00:00:00:00
sleepTime: 00:00
sleepType: Seconds
startHeld: false
startHeldReason: null
summary: Sleep for 0 seconds.
sysId: 410d6c0bc0a801c901838d8ac43b3279
timeZonePref: -- System Default --
type: taskSleep
userEstimatedDuration: null
variables: []
version: 5
virtualResources: []
