actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
avgRunTime: 7076
avgRunTimeDisplay: 1 Hour 57 Minutes 56 Seconds
calculateCp: false
calendar: null
cpDuration: null
cpDurationUnit: Minutes
criticalEndpoints: []
customField1:
  label: null
  value: null
customField2:
  label: null
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
enforceVariables: false
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.6.3.2
exportTable: ops_task_workflow
firstRun: 2025-03-21 05:57:21 -0400
holdResources: false
instanceWait: -- None --
lastRun: 2025-07-15 04:37:14 -0400
lastRunTime: 68797
lastRunTimeDisplay: 19 Hours 6 Minutes 37 Seconds
layoutOption: -- None --
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
lockVariables: false
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 68797
maxRunTimeDisplay: 19 Hours 6 Minutes 37 Seconds
minRunTime: 4
minRunTimeDisplay: 4 Seconds
name: WST
notes: []
numberOfTasks: 3
opswiseGroups: []
overrideCalendar: false
overrideInstanceWait: 'No'
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 10
runCriteria: []
runTime: 70759
simulation: false
skippedOption: Show Skipped
startHeld: false
startHeldReason: null
stepActions: []
stepConditions: []
summary: null
sysId: 1e6d0457f6e64361b43c506a0e6467a8
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskWorkflow
userEstimatedDuration: null
variables: []
version: 4
virtualResources: []
workflowEdges:
- condition:
    value: Success
  sourceId:
    taskName: Sleep 0
    value: '4'
  straightEdge: true
  targetId:
    taskName: test3
    value: '5'
workflowVertices:
- alias: null
  task:
    value: Sleep 0
  vertexId: '4'
  vertexX: '780'
  vertexY: '150'
- alias: null
  task:
    value: test3
  vertexId: '5'
  vertexX: '800'
  vertexY: '530'
- alias: null
  task:
    value: pythrun
  vertexId: '8'
  vertexX: '610'
  vertexY: '150'
